### ISSUE TITLE
final_path reference issue

### ISSUE THREAD

**Issue by saniyasahdev** [bio-guoda/hdfs-ceph-client#1]
@godfoder 
I tried running the job with the instructions given but there seems to be issue with referencing of final_path.

![image](https://user-images.githubusercontent.com/26529004/28432452-f0309566-6d55-11e7-96e4-0ea833ad9896.png)
 
The code for my job is as follows, in case I missed something. https://github.com/acislab/idigbio_distinctvalues_R/blob/master/Jenkins_ceph_sample

Thanks.

**Comment by godfoder** [comment]
The path should be in the form of /outputs/ACountryDFSS.csv , without any of the server or protocol information. I'll look into tweaking the code to be more tolerant of other path forms.
